--- 
- name: Install packages
  apt: name={{item}} state=latest update_cache=yes
  with_items:
        - python3.6
        - git
        - python-pip
        - python3-pip
        - python-virtualenv
        - sqlite3
        - nginx
        - runit
  register:  packages

- name: Create a virtualenv directory
  file: path={{deploy_dir}} state=directory

- name: Install dependencies
  pip:
     virtualenv: "{{deploy_dir}}"
     virtualenv_python: python3.6
     requirements: "{{requirements}}"

     #- name: unlink default nginx
     # command: unlink /etc/nginx/sites-enabled/default
     # when: packages

- name: Setup nginx conf
  copy: src=nginx.conf dest=/etc/nginx/sites-enabled/kvstore
  notify:
    - restart nginx

- name: Create a directory to run in supervisor mode
  file: path=/opt/kvstore.run state=directory

- name: supervisor mode on
  template:
     src: run.j2
     dest: /opt/kvstore.run/run
     mode: 0777

- name: create symlink to run in supervisor mode
  file: 
    src: /opt/kvstore.run
    dest: /etc/service/kvstore
    state: link
  notify:
    - restart gunicorn

